import fs from "fs/promises";
import path from "path";

import { logger } from "../../logging/index.js";
import { getCachedGeneratedFilesDirent } from "./getGeneratedFilesDirent.js";
import { getStaleGeneratedFiles } from "./getStaleGeneratedFiles.js";

/**
 * Delete stale generated files that were previously generated by cogenie steps.
 */
export async function deleteStaleGeneratedFiles() {
  const generatedFilesToDelete = await getStaleGeneratedFiles();

  // Delete the file and map back the promise to await together later
  const generatedFilesDeletionPromises = generatedFilesToDelete.map(
    async (file) => {
      const fullFilePath = path.resolve(file.parentPath, file.name);
      await fs.rm(fullFilePath);
      return fullFilePath;
    },
  );

  // Wait for all files to be deleted
  const deletedFiles = await Promise.all(generatedFilesDeletionPromises);

  if (deletedFiles.length > 0) {
    const generatedFilesDirent = await getCachedGeneratedFilesDirent();

    logger.info(
      deleteStaleGeneratedFiles.name,
      `Deleted ${deletedFiles.length}/${generatedFilesDirent.length} generated files:`,
    );

    for (let i = 0; i < deletedFiles.length; i++) {
      logger.info(
        deleteStaleGeneratedFiles.name,
        `Deleted file ${i + 1}: ${deletedFiles[i]}`,
      );
    }
  } else {
    logger.info(
      deleteStaleGeneratedFiles.name,
      "No generated files deleted but some may still be overwritten",
    );
  }
}
