import { getAllCogenieSteps } from "./getAllCogenieSteps.js";
import { getCachedGeneratedFilesDirent } from "./getGeneratedFilesDirent.js";

/**
 * Return stale generated files that were previously generated by cogenie steps.
 *
 * ## What is a stale generated file?
 * If the output file(s) of a cogenie step changes, e.g. the output file is
 * renamed, during the next run the originally generated file will still be
 * there and the new one will also appear. But since the old file is no longer
 * used it is considered to be a "stale file" in our version control.
 *
 * ## How?
 * This function get all new output files of all cogenie steps, and look for
 * existing generated files that is not in this set of expected output files.
 */
export async function getStaleGeneratedFiles() {
  const cogenieSteps = await getAllCogenieSteps().then((CogenieSteps) =>
    CogenieSteps.map((CogenieStep) => new CogenieStep()),
  );

  const cogenieStepsGeneratedFileTargets = cogenieSteps
    .map((cogenieStep) => Object.values(cogenieStep.getFiles()))
    .flat()
    .map((fileTarget) => fileTarget.name + fileTarget.extension);

  const cogenieStepsGeneratedFileTargetsSet = new Set(
    cogenieStepsGeneratedFileTargets,
  );

  const generatedFilesDirent = await getCachedGeneratedFilesDirent();

  // Files are stale if they are no longer in the generated file targets set
  const staleGeneratedFiles = generatedFilesDirent.filter(
    (file) => !cogenieStepsGeneratedFileTargetsSet.has(file.name),
  );

  return staleGeneratedFiles;
}
