import ts from "typescript";

import { EntSchema } from "../lib/EntSchema.js";
import { EntSchemaCodegenError } from "./EntSchemaCodegenError.js";
import { getNewline } from "./utils/getNewline.js";
import { prefixJsdocComment } from "./utils/prefixJsdocComment.js";

/**
 * @todo
 * Generates the TS AST node for the generated Ent
 */
export function generateEntOperatorsFromEntSchema(
  entSchema: EntSchema,
  config: {
    entClassName: string;
  },
) {
  const entTypeID = "";

  // ts.factory.createImportDeclaration(
  //   undefined,
  //   ts.factory.createImportClause(
  //     undefined,
  //     undefined,
  //     ts.factory.createNamedImports([
  //       ts.factory.createImportSpecifier(
  //         false,
  //         undefined,
  //         ts.factory.createIdentifier("apiDB"),
  //       ),
  //     ]),
  //   ),
  //   ts.factory.createStringLiteral("../../dal/kysely/index.js"),
  //   undefined,
  // ),
  return ts.factory.createVariableStatement(
    [ts.factory.createToken(ts.SyntaxKind.ExportKeyword)],
    ts.factory.createVariableDeclarationList(
      [
        ts.factory.createVariableDeclaration(
          ts.factory.createIdentifier("EntBlogOperators"),
          undefined,
          undefined,
          ts.factory.createCallExpression(
            ts.factory.createIdentifier("defineEntOperators"),
            undefined,
            [
              ts.factory.createIdentifier("EntBlog"),
              ts.factory.createObjectLiteralExpression(
                [
                  ts.factory.createPropertyAssignment(
                    ts.factory.createIdentifier("CRUD"),
                    ts.factory.createObjectLiteralExpression(
                      [
                        ts.factory.createMethodDeclaration(
                          [ts.factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                          undefined,
                          ts.factory.createIdentifier("create"),
                          undefined,
                          undefined,
                          [
                            ts.factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              ts.factory.createIdentifier("ent"),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          ts.factory.createBlock(
                            [
                              ts.factory.createExpressionStatement(
                                ts.factory.createAwaitExpression(
                                  ts.factory.createCallExpression(
                                    ts.factory.createPropertyAccessExpression(
                                      ts.factory.createCallExpression(
                                        ts.factory.createPropertyAccessExpression(
                                          ts.factory.createCallExpression(
                                            ts.factory.createPropertyAccessExpression(
                                              ts.factory.createCallExpression(
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "apiDB",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "insertInto",
                                                  ),
                                                ),
                                                undefined,
                                                [
                                                  ts.factory.createStringLiteral(
                                                    "blog",
                                                  ),
                                                ],
                                              ),
                                              ts.factory.createIdentifier(
                                                "values",
                                              ),
                                            ),
                                            undefined,
                                            [
                                              ts.factory.createObjectLiteralExpression(
                                                [
                                                  ts.factory.createPropertyAssignment(
                                                    ts.factory.createIdentifier(
                                                      "id",
                                                    ),
                                                    ts.factory.createPropertyAccessExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "ent",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "data",
                                                        ),
                                                      ),
                                                      ts.factory.createIdentifier(
                                                        "id",
                                                      ),
                                                    ),
                                                  ),
                                                  ts.factory.createPropertyAssignment(
                                                    ts.factory.createIdentifier(
                                                      "created_at",
                                                    ),
                                                    ts.factory.createPropertyAccessExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "ent",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "data",
                                                        ),
                                                      ),
                                                      ts.factory.createIdentifier(
                                                        "createdAt",
                                                      ),
                                                    ),
                                                  ),
                                                  ts.factory.createPropertyAssignment(
                                                    ts.factory.createIdentifier(
                                                      "updated_at",
                                                    ),
                                                    ts.factory.createPropertyAccessExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "ent",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "data",
                                                        ),
                                                      ),
                                                      ts.factory.createIdentifier(
                                                        "updatedAt",
                                                      ),
                                                    ),
                                                  ),
                                                  ts.factory.createPropertyAssignment(
                                                    ts.factory.createIdentifier(
                                                      "name",
                                                    ),
                                                    ts.factory.createPropertyAccessExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "ent",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "data",
                                                        ),
                                                      ),
                                                      ts.factory.createIdentifier(
                                                        "name",
                                                      ),
                                                    ),
                                                  ),
                                                  ts.factory.createPropertyAssignment(
                                                    ts.factory.createIdentifier(
                                                      "owner_email",
                                                    ),
                                                    ts.factory.createPropertyAccessExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "ent",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "data",
                                                        ),
                                                      ),
                                                      ts.factory.createIdentifier(
                                                        "ownerEmail",
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                                true,
                                              ),
                                            ],
                                          ),
                                          ts.factory.createIdentifier(
                                            "returningAll",
                                          ),
                                        ),
                                        undefined,
                                        [],
                                      ),
                                      ts.factory.createIdentifier(
                                        "executeTakeFirstOrThrow",
                                      ),
                                    ),
                                    undefined,
                                    [],
                                  ),
                                ),
                              ),
                            ],
                            true,
                          ),
                        ),
                        ts.factory.createMethodDeclaration(
                          [ts.factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                          undefined,
                          ts.factory.createIdentifier("get"),
                          undefined,
                          undefined,
                          [
                            ts.factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              ts.factory.createIdentifier("id"),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          ts.factory.createBlock(
                            [
                              ts.factory.createVariableStatement(
                                undefined,
                                ts.factory.createVariableDeclarationList(
                                  [
                                    ts.factory.createVariableDeclaration(
                                      ts.factory.createIdentifier("data"),
                                      undefined,
                                      undefined,
                                      ts.factory.createAwaitExpression(
                                        ts.factory.createCallExpression(
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createCallExpression(
                                              ts.factory.createPropertyAccessExpression(
                                                ts.factory.createCallExpression(
                                                  ts.factory.createPropertyAccessExpression(
                                                    ts.factory.createCallExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "apiDB",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "selectFrom",
                                                        ),
                                                      ),
                                                      undefined,
                                                      [
                                                        ts.factory.createStringLiteral(
                                                          "blog",
                                                        ),
                                                      ],
                                                    ),
                                                    ts.factory.createIdentifier(
                                                      "selectAll",
                                                    ),
                                                  ),
                                                  undefined,
                                                  [],
                                                ),
                                                ts.factory.createIdentifier(
                                                  "where",
                                                ),
                                              ),
                                              undefined,
                                              [
                                                ts.factory.createStringLiteral(
                                                  "id",
                                                ),
                                                ts.factory.createStringLiteral(
                                                  "=",
                                                ),
                                                ts.factory.createIdentifier(
                                                  "id",
                                                ),
                                              ],
                                            ),
                                            ts.factory.createIdentifier(
                                              "executeTakeFirstOrThrow",
                                            ),
                                          ),
                                          undefined,
                                          [],
                                        ),
                                      ),
                                    ),
                                  ],
                                  ts.NodeFlags.Const,
                                ),
                              ),
                              ts.factory.createReturnStatement(
                                ts.factory.createNewExpression(
                                  ts.factory.createIdentifier("EntBlog"),
                                  undefined,
                                  [
                                    ts.factory.createObjectLiteralExpression(
                                      [
                                        ts.factory.createPropertyAssignment(
                                          ts.factory.createIdentifier("id"),
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createIdentifier("data"),
                                            ts.factory.createIdentifier("id"),
                                          ),
                                        ),
                                        ts.factory.createPropertyAssignment(
                                          ts.factory.createIdentifier(
                                            "createdAt",
                                          ),
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createIdentifier("data"),
                                            ts.factory.createIdentifier(
                                              "created_at",
                                            ),
                                          ),
                                        ),
                                        ts.factory.createPropertyAssignment(
                                          ts.factory.createIdentifier(
                                            "updatedAt",
                                          ),
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createIdentifier("data"),
                                            ts.factory.createIdentifier(
                                              "updated_at",
                                            ),
                                          ),
                                        ),
                                        ts.factory.createPropertyAssignment(
                                          ts.factory.createIdentifier("name"),
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createIdentifier("data"),
                                            ts.factory.createIdentifier("name"),
                                          ),
                                        ),
                                        ts.factory.createPropertyAssignment(
                                          ts.factory.createIdentifier(
                                            "ownerEmail",
                                          ),
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createIdentifier("data"),
                                            ts.factory.createIdentifier(
                                              "owner_email",
                                            ),
                                          ),
                                        ),
                                      ],
                                      true,
                                    ),
                                  ],
                                ),
                              ),
                            ],
                            true,
                          ),
                        ),
                        ts.factory.createMethodDeclaration(
                          [ts.factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                          undefined,
                          ts.factory.createIdentifier("getMany"),
                          undefined,
                          undefined,
                          [
                            ts.factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              ts.factory.createIdentifier("ids"),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          ts.factory.createBlock(
                            [
                              ts.factory.createVariableStatement(
                                undefined,
                                ts.factory.createVariableDeclarationList(
                                  [
                                    ts.factory.createVariableDeclaration(
                                      ts.factory.createIdentifier("data"),
                                      undefined,
                                      undefined,
                                      ts.factory.createAwaitExpression(
                                        ts.factory.createCallExpression(
                                          ts.factory.createPropertyAccessExpression(
                                            ts.factory.createCallExpression(
                                              ts.factory.createPropertyAccessExpression(
                                                ts.factory.createCallExpression(
                                                  ts.factory.createPropertyAccessExpression(
                                                    ts.factory.createCallExpression(
                                                      ts.factory.createPropertyAccessExpression(
                                                        ts.factory.createIdentifier(
                                                          "apiDB",
                                                        ),
                                                        ts.factory.createIdentifier(
                                                          "selectFrom",
                                                        ),
                                                      ),
                                                      undefined,
                                                      [
                                                        ts.factory.createStringLiteral(
                                                          "blog",
                                                        ),
                                                      ],
                                                    ),
                                                    ts.factory.createIdentifier(
                                                      "selectAll",
                                                    ),
                                                  ),
                                                  undefined,
                                                  [],
                                                ),
                                                ts.factory.createIdentifier(
                                                  "where",
                                                ),
                                              ),
                                              undefined,
                                              [
                                                ts.factory.createStringLiteral(
                                                  "id",
                                                ),
                                                ts.factory.createStringLiteral(
                                                  "in",
                                                ),
                                                ts.factory.createIdentifier(
                                                  "ids",
                                                ),
                                              ],
                                            ),
                                            ts.factory.createIdentifier(
                                              "execute",
                                            ),
                                          ),
                                          undefined,
                                          [],
                                        ),
                                      ),
                                    ),
                                  ],
                                  ts.NodeFlags.Const,
                                ),
                              ),
                              ts.factory.createReturnStatement(
                                ts.factory.createCallExpression(
                                  ts.factory.createPropertyAccessExpression(
                                    ts.factory.createIdentifier("data"),
                                    ts.factory.createIdentifier("map"),
                                  ),
                                  undefined,
                                  [
                                    ts.factory.createArrowFunction(
                                      undefined,
                                      undefined,
                                      [
                                        ts.factory.createParameterDeclaration(
                                          undefined,
                                          undefined,
                                          ts.factory.createIdentifier("data"),
                                          undefined,
                                          undefined,
                                          undefined,
                                        ),
                                      ],
                                      undefined,
                                      ts.factory.createToken(
                                        ts.SyntaxKind.EqualsGreaterThanToken,
                                      ),
                                      ts.factory.createNewExpression(
                                        ts.factory.createIdentifier("EntBlog"),
                                        undefined,
                                        [
                                          ts.factory.createObjectLiteralExpression(
                                            [
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "id",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "id",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "createdAt",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "created_at",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "updatedAt",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "updated_at",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "name",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "name",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "ownerEmail",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "owner_email",
                                                  ),
                                                ),
                                              ),
                                            ],
                                            true,
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                            true,
                          ),
                        ),
                        ts.factory.createMethodDeclaration(
                          [ts.factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                          undefined,
                          ts.factory.createIdentifier("update"),
                          undefined,
                          undefined,
                          [
                            ts.factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              ts.factory.createIdentifier("ent"),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          ts.factory.createBlock(
                            [
                              ts.factory.createExpressionStatement(
                                ts.factory.createAwaitExpression(
                                  ts.factory.createCallExpression(
                                    ts.factory.createPropertyAccessExpression(
                                      ts.factory.createCallExpression(
                                        ts.factory.createPropertyAccessExpression(
                                          ts.factory.createCallExpression(
                                            ts.factory.createPropertyAccessExpression(
                                              ts.factory.createCallExpression(
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "apiDB",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "updateTable",
                                                  ),
                                                ),
                                                undefined,
                                                [
                                                  ts.factory.createStringLiteral(
                                                    "blog",
                                                  ),
                                                ],
                                              ),
                                              ts.factory.createIdentifier(
                                                "where",
                                              ),
                                            ),
                                            undefined,
                                            [
                                              ts.factory.createStringLiteral(
                                                "id",
                                              ),
                                              ts.factory.createStringLiteral(
                                                "=",
                                              ),
                                              ts.factory.createPropertyAccessExpression(
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "ent",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "data",
                                                  ),
                                                ),
                                                ts.factory.createIdentifier(
                                                  "id",
                                                ),
                                              ),
                                            ],
                                          ),
                                          ts.factory.createIdentifier("set"),
                                        ),
                                        undefined,
                                        [
                                          ts.factory.createObjectLiteralExpression(
                                            [
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "updated_at",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createPropertyAccessExpression(
                                                    ts.factory.createIdentifier(
                                                      "ent",
                                                    ),
                                                    ts.factory.createIdentifier(
                                                      "data",
                                                    ),
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "updatedAt",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "name",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createPropertyAccessExpression(
                                                    ts.factory.createIdentifier(
                                                      "ent",
                                                    ),
                                                    ts.factory.createIdentifier(
                                                      "data",
                                                    ),
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "name",
                                                  ),
                                                ),
                                              ),
                                              ts.factory.createPropertyAssignment(
                                                ts.factory.createIdentifier(
                                                  "owner_email",
                                                ),
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createPropertyAccessExpression(
                                                    ts.factory.createIdentifier(
                                                      "ent",
                                                    ),
                                                    ts.factory.createIdentifier(
                                                      "data",
                                                    ),
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "ownerEmail",
                                                  ),
                                                ),
                                              ),
                                            ],
                                            true,
                                          ),
                                        ],
                                      ),
                                      ts.factory.createIdentifier("execute"),
                                    ),
                                    undefined,
                                    [],
                                  ),
                                ),
                              ),
                            ],
                            true,
                          ),
                        ),
                        ts.factory.createMethodDeclaration(
                          [ts.factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                          undefined,
                          ts.factory.createIdentifier("delete"),
                          undefined,
                          undefined,
                          [
                            ts.factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              ts.factory.createIdentifier("id"),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          ts.factory.createBlock(
                            [
                              ts.factory.createExpressionStatement(
                                ts.factory.createAwaitExpression(
                                  ts.factory.createCallExpression(
                                    ts.factory.createPropertyAccessExpression(
                                      ts.factory.createCallExpression(
                                        ts.factory.createPropertyAccessExpression(
                                          ts.factory.createCallExpression(
                                            ts.factory.createPropertyAccessExpression(
                                              ts.factory.createCallExpression(
                                                ts.factory.createPropertyAccessExpression(
                                                  ts.factory.createIdentifier(
                                                    "apiDB",
                                                  ),
                                                  ts.factory.createIdentifier(
                                                    "deleteFrom",
                                                  ),
                                                ),
                                                undefined,
                                                [
                                                  ts.factory.createStringLiteral(
                                                    "blog",
                                                  ),
                                                ],
                                              ),
                                              ts.factory.createIdentifier(
                                                "where",
                                              ),
                                            ),
                                            undefined,
                                            [
                                              ts.factory.createStringLiteral(
                                                "id",
                                              ),
                                              ts.factory.createStringLiteral(
                                                "=",
                                              ),
                                              ts.factory.createIdentifier("id"),
                                            ],
                                          ),
                                          ts.factory.createIdentifier(
                                            "returningAll",
                                          ),
                                        ),
                                        undefined,
                                        [],
                                      ),
                                      ts.factory.createIdentifier(
                                        "executeTakeFirst",
                                      ),
                                    ),
                                    undefined,
                                    [],
                                  ),
                                ),
                              ),
                            ],
                            true,
                          ),
                        ),
                      ],
                      true,
                    ),
                  ),
                  ts.factory.createPropertyAssignment(
                    ts.factory.createIdentifier("custom"),
                    ts.factory.createObjectLiteralExpression([], false),
                  ),
                ],
                true,
              ),
            ],
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );
}
