/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenAsyncJobTypeBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(d67098ea305a8c0177641ddacdc83afd8430b1637f778519b6d11db0efe6df06)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as example } from "../async/jobs/example.job.js";
