/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genAsyncJobTypeMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(597c2eae6d6b9c9581961eeafa5e52497784c91e78d03ffd2d8112a22e8707e2)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { AsyncJobType } from "../async/AsyncJobType.js";

/**
 * Mapping of `AsyncJobType['ID']` to `AsyncJobType`.
 *
 * Use `import` function to asynchronously load the job definition module, so
 * that they are not all loaded on startup and only lazily loaded whenever they
 * are used.
 */
export const asyncJobTypeMapping: Record<
  string,
  () => Promise<{ default: AsyncJobType<any> }>
> = {
  "3h1s": () => import("../async/jobs/example.job.js"),
};
