/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenAsyncJobTypeMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(6ba958c0d931d76eab1849f037e502807f13962d45035a32ebccb42a21ea4af5)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { AsyncJobType } from "../async/AsyncJobType.js";

/**
 * Mapping of `AsyncJobType['ID']` to `AsyncJobType`.
 *
 * Use `import` function to asynchronously load the job definition module, so
 * that they are not all loaded on startup and only lazily loaded whenever they
 * are used.
 */
export const asyncJobTypeMapping: Record<
  string,
  () => Promise<{ default: AsyncJobType<any> }>
> = {
  "3h1s": () => import("../async/jobs/example.job.js"),
};
