/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genAsyncJobTypeBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(4ab9f4f5dc6c3e759d4e0d623b90d2757bfe29d94f14636e504313669abdd4f2)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as example } from "../async/jobs/example.job.js";
