/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genAsyncJobTypeMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(4c805c66c1cfc40144acea9f05770d568780e103be85ae3c4ef86d246974600c)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { AsyncJobType } from "../async/AsyncJobType.js";

/**
 * Mapping of `AsyncJobType['ID']` to `AsyncJobType`.
 *
 * Use `import` function to asynchronously load the job definition module, so
 * that they are not all loaded on startup and only lazily loaded whenever they
 * are used.
 */
export const asyncJobTypeMapping: Record<
  string,
  () => Promise<{ default: AsyncJobType<any> }>
> = {
  "186e39bb-0bd5-451c-8a90-557ae9a54ca8": () =>
    import("../async/jobs/example.job.js"),
};
