/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genEntMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(0447b9ee534ee8fbd2f1c49911bef29d311ddf7fb7c9e010b49528a968c86e84)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { BaseEnt } from "../ent/BaseEnt.js";

import { ents } from "./entsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `Ent`.
 */
export const entMapping: Record<
  string,
  new (..._constructorArgs: any) => BaseEnt<any>
> = {
  "40ba": ents.EntBlog,
  "0dda": ents.EntBlogSubscriber,
  "4f51": ents.EntJohari,
  "90f3": ents.EntJohariAnswer,
  "48fi": ents.EntUser,
};
