/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenEntMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(afe854299f738103c83d6ff1d059727ee29b55198e993a01cf7a3fde3a347198)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { BaseEnt } from "../ent/BaseEnt.js";

import { ents } from "./entsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `Ent`.
 */
export const entMapping: Record<
  string,
  new (..._constructorArgs: any) => BaseEnt<any>
> = {
  "40ba": ents.EntBlog,
  "0dda": ents.EntBlogSubscriber,
  "4f51": ents.EntJohari,
  "90f3": ents.EntJohariAnswer,
  "48fi": ents.EntUser,
};
