/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genEntMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(7085396dce7aa7cc31657c447875ac25b07ee43a2a6548115b5dd18c5a3395a7)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import { ents } from "./entsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `Ent`.
 */
export const entMapping = {
  "40ba": ents.EntBlog,
  "0dda": ents.EntBlogSubscriber,
  "4f51": ents.EntJohari,
  "90f3": ents.EntJohariAnswer,
};
