/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenEntOperatorMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(532bab09ecf8282b37b1155a6763ff37a8bc5e732f314bc8c033117015c57463)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { BaseEnt } from "../ent/BaseEnt.js";
import type { EntCrudOperator } from "../ent/EntCrudOperator.js";

import { entOperators } from "./entOperatorsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `EntOperators`.
 */
export const entOperatorsMapping: Record<string, EntCrudOperator<BaseEnt>> = {
  "40ba": entOperators.EntBlogOperators,
  "0dda": entOperators.EntBlogSubscriberOperators,
  "4f51": entOperators.EntJohariOperators,
  "90f3": entOperators.EntJohariAnswerOperators,
  "48fi": entOperators.EntUserOperators,
};
