/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genEntOperatorMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(630e080271c3041ac326e954405cb49d0cf7bcc346d4efca9e7f44eef186174b)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { BaseEnt } from "../ent/BaseEnt.js";
import type { EntCrudOperator } from "../ent/EntCrudOperator.js";

import { entOperators } from "./entOperatorsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `EntOperators`.
 */
export const entOperatorsMapping: Record<string, EntCrudOperator<BaseEnt>> = {
  "40ba": entOperators.EntBlogOperators,
  "0dda": entOperators.EntBlogSubscriberOperators,
  "4f51": entOperators.EntJohariOperators,
  "90f3": entOperators.EntJohariAnswerOperators,
  "48fi": entOperators.EntUserOperators,
};
