/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpDtoTypeDefinition
 *
 * Generated hash in hex for code after this section is:
 * sha256(f0925ab27bb38c03d867fc0e817f2613bcc368c6fc170f21099a270fe40319f2)
 */
import type { z } from "zod";
import * as c from "./httpControllerBarrelFile.generated.do_not_include_in_barrel_file.js";

export type healthCheckController_QueryParams = z.infer<
  Exclude<(typeof c.healthCheck)["urlQueryParamsValidator"], null>
>;
export type healthCheckController_InputDTO = z.infer<
  Exclude<(typeof c.healthCheck)["requestBodyValidator"], null>
>;
export type healthCheckController_OutputDTO = Awaited<
  ReturnType<(typeof c.healthCheck)["httpRequestHandler"]>
>;
export type blogBlogNewSubscriberController_QueryParams = z.infer<
  Exclude<(typeof c.blogBlogNewSubscriber)["urlQueryParamsValidator"], null>
>;
export type blogBlogNewSubscriberController_InputDTO = z.infer<
  Exclude<(typeof c.blogBlogNewSubscriber)["requestBodyValidator"], null>
>;
export type blogBlogNewSubscriberController_OutputDTO = Awaited<
  ReturnType<(typeof c.blogBlogNewSubscriber)["httpRequestHandler"]>
>;
export type bucketlistCreateBucketlistController_QueryParams = z.infer<
  Exclude<
    (typeof c.bucketlistCreateBucketlist)["urlQueryParamsValidator"],
    null
  >
>;
export type bucketlistCreateBucketlistController_InputDTO = z.infer<
  Exclude<(typeof c.bucketlistCreateBucketlist)["requestBodyValidator"], null>
>;
export type bucketlistCreateBucketlistController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistCreateBucketlist)["httpRequestHandler"]>
>;
export type bucketlistGetBucketlistController_QueryParams = z.infer<
  Exclude<(typeof c.bucketlistGetBucketlist)["urlQueryParamsValidator"], null>
>;
export type bucketlistGetBucketlistController_InputDTO = z.infer<
  Exclude<(typeof c.bucketlistGetBucketlist)["requestBodyValidator"], null>
>;
export type bucketlistGetBucketlistController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistGetBucketlist)["httpRequestHandler"]>
>;
export type leetcodeCreateLeetcodeQuesController_QueryParams = z.infer<
  Exclude<
    (typeof c.leetcodeCreateLeetcodeQues)["urlQueryParamsValidator"],
    null
  >
>;
export type leetcodeCreateLeetcodeQuesController_InputDTO = z.infer<
  Exclude<(typeof c.leetcodeCreateLeetcodeQues)["requestBodyValidator"], null>
>;
export type leetcodeCreateLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeCreateLeetcodeQues)["httpRequestHandler"]>
>;
export type leetcodeGetLeetcodeQuesController_QueryParams = z.infer<
  Exclude<(typeof c.leetcodeGetLeetcodeQues)["urlQueryParamsValidator"], null>
>;
export type leetcodeGetLeetcodeQuesController_InputDTO = z.infer<
  Exclude<(typeof c.leetcodeGetLeetcodeQues)["requestBodyValidator"], null>
>;
export type leetcodeGetLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeGetLeetcodeQues)["httpRequestHandler"]>
>;
export type versionController_QueryParams = z.infer<
  Exclude<(typeof c.version)["urlQueryParamsValidator"], null>
>;
export type versionController_InputDTO = z.infer<
  Exclude<(typeof c.version)["requestBodyValidator"], null>
>;
export type versionController_OutputDTO = Awaited<
  ReturnType<(typeof c.version)["httpRequestHandler"]>
>;
