/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpDtoTypeDefinition
 *
 * Generated hash in hex for code after this section is:
 * sha256(2182c5ce87d8c77f102bbce293fb2669787d7b7fe88828fa26eddf6f8f0dbf36)
 */
import type { z } from "zod";
import * as c from "./httpControllerBarrelFile.generated.js";

export type healthCheck_QueryParams = z.infer<
  Exclude<(typeof c.healthCheck)["urlQueryParamsValidator"], null>
>;
export type healthCheck_InputDTO = z.infer<
  Exclude<(typeof c.healthCheck)["requestBodyValidator"], null>
>;
export type healthCheck_OutputDTO = Awaited<
  ReturnType<(typeof c.healthCheck)["httpRequestHandler"]>
>;
export type blogNewSubscriberController_QueryParams = z.infer<
  Exclude<
    (typeof c.blogNewSubscriberController)["urlQueryParamsValidator"],
    null
  >
>;
export type blogNewSubscriberController_InputDTO = z.infer<
  Exclude<(typeof c.blogNewSubscriberController)["requestBodyValidator"], null>
>;
export type blogNewSubscriberController_OutputDTO = Awaited<
  ReturnType<(typeof c.blogNewSubscriberController)["httpRequestHandler"]>
>;
export type createBucketlistController_QueryParams = z.infer<
  Exclude<
    (typeof c.createBucketlistController)["urlQueryParamsValidator"],
    null
  >
>;
export type createBucketlistController_InputDTO = z.infer<
  Exclude<(typeof c.createBucketlistController)["requestBodyValidator"], null>
>;
export type createBucketlistController_OutputDTO = Awaited<
  ReturnType<(typeof c.createBucketlistController)["httpRequestHandler"]>
>;
export type getBucketlistController_QueryParams = z.infer<
  Exclude<(typeof c.getBucketlistController)["urlQueryParamsValidator"], null>
>;
export type getBucketlistController_InputDTO = z.infer<
  Exclude<(typeof c.getBucketlistController)["requestBodyValidator"], null>
>;
export type getBucketlistController_OutputDTO = Awaited<
  ReturnType<(typeof c.getBucketlistController)["httpRequestHandler"]>
>;
export type version_QueryParams = z.infer<
  Exclude<(typeof c.version)["urlQueryParamsValidator"], null>
>;
export type version_InputDTO = z.infer<
  Exclude<(typeof c.version)["requestBodyValidator"], null>
>;
export type version_OutputDTO = Awaited<
  ReturnType<(typeof c.version)["httpRequestHandler"]>
>;
