/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpControllerTypeDefinitions
 *
 * Generated hash in hex for code after this section is:
 * sha256(f83a3f6a305bd9e3757863fd91c260a95614290a18900ad2467a5cd52c5a24c9)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { z } from "zod";
import type { JSendSuccess } from "../http/JSend.js";
import * as c from "./httpControllerBarrelFile.generated.do_not_include_in_barrel_file.js";

export type healthCheckController_UrlParams = z.infer<
  Exclude<(typeof c.healthCheck)["urlParamsValidator"], null>
>;
export type healthCheckController_QueryParams = z.infer<
  Exclude<(typeof c.healthCheck)["urlQueryParamsValidator"], null>
>;
export type healthCheckController_InputDTO = z.infer<
  Exclude<(typeof c.healthCheck)["requestBodyValidator"], null>
>;
export type healthCheckController_OutputDTO = Awaited<
  ReturnType<(typeof c.healthCheck)["httpRequestHandler"]>
>;
export type healthCheckController_OutputFullDTO =
  JSendSuccess<healthCheckController_OutputDTO>;
export type blogNewSubscriberController_UrlParams = z.infer<
  Exclude<(typeof c.blogNewSubscriber)["urlParamsValidator"], null>
>;
export type blogNewSubscriberController_QueryParams = z.infer<
  Exclude<(typeof c.blogNewSubscriber)["urlQueryParamsValidator"], null>
>;
export type blogNewSubscriberController_InputDTO = z.infer<
  Exclude<(typeof c.blogNewSubscriber)["requestBodyValidator"], null>
>;
export type blogNewSubscriberController_OutputDTO = Awaited<
  ReturnType<(typeof c.blogNewSubscriber)["httpRequestHandler"]>
>;
export type blogNewSubscriberController_OutputFullDTO =
  JSendSuccess<blogNewSubscriberController_OutputDTO>;
export type bucketlistCreateOneController_UrlParams = z.infer<
  Exclude<(typeof c.bucketlistCreateOne)["urlParamsValidator"], null>
>;
export type bucketlistCreateOneController_QueryParams = z.infer<
  Exclude<(typeof c.bucketlistCreateOne)["urlQueryParamsValidator"], null>
>;
export type bucketlistCreateOneController_InputDTO = z.infer<
  Exclude<(typeof c.bucketlistCreateOne)["requestBodyValidator"], null>
>;
export type bucketlistCreateOneController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistCreateOne)["httpRequestHandler"]>
>;
export type bucketlistCreateOneController_OutputFullDTO =
  JSendSuccess<bucketlistCreateOneController_OutputDTO>;
export type bucketlistGetOneController_UrlParams = z.infer<
  Exclude<(typeof c.bucketlistGetOne)["urlParamsValidator"], null>
>;
export type bucketlistGetOneController_QueryParams = z.infer<
  Exclude<(typeof c.bucketlistGetOne)["urlQueryParamsValidator"], null>
>;
export type bucketlistGetOneController_InputDTO = z.infer<
  Exclude<(typeof c.bucketlistGetOne)["requestBodyValidator"], null>
>;
export type bucketlistGetOneController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistGetOne)["httpRequestHandler"]>
>;
export type bucketlistGetOneController_OutputFullDTO =
  JSendSuccess<bucketlistGetOneController_OutputDTO>;
export type checkGetChecklistController_UrlParams = z.infer<
  Exclude<(typeof c.checkGetChecklist)["urlParamsValidator"], null>
>;
export type checkGetChecklistController_QueryParams = z.infer<
  Exclude<(typeof c.checkGetChecklist)["urlQueryParamsValidator"], null>
>;
export type checkGetChecklistController_InputDTO = z.infer<
  Exclude<(typeof c.checkGetChecklist)["requestBodyValidator"], null>
>;
export type checkGetChecklistController_OutputDTO = Awaited<
  ReturnType<(typeof c.checkGetChecklist)["httpRequestHandler"]>
>;
export type checkGetChecklistController_OutputFullDTO =
  JSendSuccess<checkGetChecklistController_OutputDTO>;
export type johariCreateJohariController_UrlParams = z.infer<
  Exclude<(typeof c.johariCreateJohari)["urlParamsValidator"], null>
>;
export type johariCreateJohariController_QueryParams = z.infer<
  Exclude<(typeof c.johariCreateJohari)["urlQueryParamsValidator"], null>
>;
export type johariCreateJohariController_InputDTO = z.infer<
  Exclude<(typeof c.johariCreateJohari)["requestBodyValidator"], null>
>;
export type johariCreateJohariController_OutputDTO = Awaited<
  ReturnType<(typeof c.johariCreateJohari)["httpRequestHandler"]>
>;
export type johariCreateJohariController_OutputFullDTO =
  JSendSuccess<johariCreateJohariController_OutputDTO>;
export type leetcodeCreateLeetcodeQuesController_UrlParams = z.infer<
  Exclude<(typeof c.leetcodeCreateLeetcodeQues)["urlParamsValidator"], null>
>;
export type leetcodeCreateLeetcodeQuesController_QueryParams = z.infer<
  Exclude<
    (typeof c.leetcodeCreateLeetcodeQues)["urlQueryParamsValidator"],
    null
  >
>;
export type leetcodeCreateLeetcodeQuesController_InputDTO = z.infer<
  Exclude<(typeof c.leetcodeCreateLeetcodeQues)["requestBodyValidator"], null>
>;
export type leetcodeCreateLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeCreateLeetcodeQues)["httpRequestHandler"]>
>;
export type leetcodeCreateLeetcodeQuesController_OutputFullDTO =
  JSendSuccess<leetcodeCreateLeetcodeQuesController_OutputDTO>;
export type leetcodeGetLeetcodeQuesController_UrlParams = z.infer<
  Exclude<(typeof c.leetcodeGetLeetcodeQues)["urlParamsValidator"], null>
>;
export type leetcodeGetLeetcodeQuesController_QueryParams = z.infer<
  Exclude<(typeof c.leetcodeGetLeetcodeQues)["urlQueryParamsValidator"], null>
>;
export type leetcodeGetLeetcodeQuesController_InputDTO = z.infer<
  Exclude<(typeof c.leetcodeGetLeetcodeQues)["requestBodyValidator"], null>
>;
export type leetcodeGetLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeGetLeetcodeQues)["httpRequestHandler"]>
>;
export type leetcodeGetLeetcodeQuesController_OutputFullDTO =
  JSendSuccess<leetcodeGetLeetcodeQuesController_OutputDTO>;
export type versionController_UrlParams = z.infer<
  Exclude<(typeof c.version)["urlParamsValidator"], null>
>;
export type versionController_QueryParams = z.infer<
  Exclude<(typeof c.version)["urlQueryParamsValidator"], null>
>;
export type versionController_InputDTO = z.infer<
  Exclude<(typeof c.version)["requestBodyValidator"], null>
>;
export type versionController_OutputDTO = Awaited<
  ReturnType<(typeof c.version)["httpRequestHandler"]>
>;
export type versionController_OutputFullDTO =
  JSendSuccess<versionController_OutputDTO>;
export type webhookTelegramController_UrlParams = z.infer<
  Exclude<(typeof c.webhookTelegram)["urlParamsValidator"], null>
>;
export type webhookTelegramController_QueryParams = z.infer<
  Exclude<(typeof c.webhookTelegram)["urlQueryParamsValidator"], null>
>;
export type webhookTelegramController_InputDTO = z.infer<
  Exclude<(typeof c.webhookTelegram)["requestBodyValidator"], null>
>;
export type webhookTelegramController_OutputDTO = Awaited<
  ReturnType<(typeof c.webhookTelegram)["httpRequestHandler"]>
>;
export type webhookTelegramController_OutputFullDTO =
  JSendSuccess<webhookTelegramController_OutputDTO>;
