/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenHttpControllerTypeDefinitions
 *
 * Generated hash in hex for code after this section is:
 * sha256(0ccc5125dce4d2432f91db951a0b46cb6c9d339738f3bbf09dc266949738a580)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { z } from "zod";
import type { JSendSuccess } from "../http/JSend.js";
import type { httpControllers as c } from "./httpControllerBarrelFile.generated.js";

export type healthCheckController_UrlParams = z.infer<
  NonNullable<(typeof c.healthCheck)["urlParamsValidator"]>
>;
export type healthCheckController_QueryParams = z.infer<
  NonNullable<(typeof c.healthCheck)["urlQueryParamsValidator"]>
>;
export type healthCheckController_InputDTO = z.infer<
  NonNullable<(typeof c.healthCheck)["requestBodyValidator"]>
>;
export type healthCheckController_OutputDTO = Awaited<
  ReturnType<(typeof c.healthCheck)["httpRequestHandler"]>
>;
export type healthCheckController_OutputFullDTO =
  JSendSuccess<healthCheckController_OutputDTO>;
export type blogNewSubscriberController_UrlParams = z.infer<
  NonNullable<(typeof c.blogNewSubscriber)["urlParamsValidator"]>
>;
export type blogNewSubscriberController_QueryParams = z.infer<
  NonNullable<(typeof c.blogNewSubscriber)["urlQueryParamsValidator"]>
>;
export type blogNewSubscriberController_InputDTO = z.infer<
  NonNullable<(typeof c.blogNewSubscriber)["requestBodyValidator"]>
>;
export type blogNewSubscriberController_OutputDTO = Awaited<
  ReturnType<(typeof c.blogNewSubscriber)["httpRequestHandler"]>
>;
export type blogNewSubscriberController_OutputFullDTO =
  JSendSuccess<blogNewSubscriberController_OutputDTO>;
export type bucketlistCreateOneController_UrlParams = z.infer<
  NonNullable<(typeof c.bucketlistCreateOne)["urlParamsValidator"]>
>;
export type bucketlistCreateOneController_QueryParams = z.infer<
  NonNullable<(typeof c.bucketlistCreateOne)["urlQueryParamsValidator"]>
>;
export type bucketlistCreateOneController_InputDTO = z.infer<
  NonNullable<(typeof c.bucketlistCreateOne)["requestBodyValidator"]>
>;
export type bucketlistCreateOneController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistCreateOne)["httpRequestHandler"]>
>;
export type bucketlistCreateOneController_OutputFullDTO =
  JSendSuccess<bucketlistCreateOneController_OutputDTO>;
export type bucketlistGetOneController_UrlParams = z.infer<
  NonNullable<(typeof c.bucketlistGetOne)["urlParamsValidator"]>
>;
export type bucketlistGetOneController_QueryParams = z.infer<
  NonNullable<(typeof c.bucketlistGetOne)["urlQueryParamsValidator"]>
>;
export type bucketlistGetOneController_InputDTO = z.infer<
  NonNullable<(typeof c.bucketlistGetOne)["requestBodyValidator"]>
>;
export type bucketlistGetOneController_OutputDTO = Awaited<
  ReturnType<(typeof c.bucketlistGetOne)["httpRequestHandler"]>
>;
export type bucketlistGetOneController_OutputFullDTO =
  JSendSuccess<bucketlistGetOneController_OutputDTO>;
export type checkGetChecklistController_UrlParams = z.infer<
  NonNullable<(typeof c.checkGetChecklist)["urlParamsValidator"]>
>;
export type checkGetChecklistController_QueryParams = z.infer<
  NonNullable<(typeof c.checkGetChecklist)["urlQueryParamsValidator"]>
>;
export type checkGetChecklistController_InputDTO = z.infer<
  NonNullable<(typeof c.checkGetChecklist)["requestBodyValidator"]>
>;
export type checkGetChecklistController_OutputDTO = Awaited<
  ReturnType<(typeof c.checkGetChecklist)["httpRequestHandler"]>
>;
export type checkGetChecklistController_OutputFullDTO =
  JSendSuccess<checkGetChecklistController_OutputDTO>;
export type johariGetJohariController_UrlParams = z.infer<
  NonNullable<(typeof c.johariGetJohari)["urlParamsValidator"]>
>;
export type johariGetJohariController_QueryParams = z.infer<
  NonNullable<(typeof c.johariGetJohari)["urlQueryParamsValidator"]>
>;
export type johariGetJohariController_InputDTO = z.infer<
  NonNullable<(typeof c.johariGetJohari)["requestBodyValidator"]>
>;
export type johariGetJohariController_OutputDTO = Awaited<
  ReturnType<(typeof c.johariGetJohari)["httpRequestHandler"]>
>;
export type johariGetJohariController_OutputFullDTO =
  JSendSuccess<johariGetJohariController_OutputDTO>;
export type johariCreateJohariAnswerController_UrlParams = z.infer<
  NonNullable<(typeof c.johariCreateJohariAnswer)["urlParamsValidator"]>
>;
export type johariCreateJohariAnswerController_QueryParams = z.infer<
  NonNullable<(typeof c.johariCreateJohariAnswer)["urlQueryParamsValidator"]>
>;
export type johariCreateJohariAnswerController_InputDTO = z.infer<
  NonNullable<(typeof c.johariCreateJohariAnswer)["requestBodyValidator"]>
>;
export type johariCreateJohariAnswerController_OutputDTO = Awaited<
  ReturnType<(typeof c.johariCreateJohariAnswer)["httpRequestHandler"]>
>;
export type johariCreateJohariAnswerController_OutputFullDTO =
  JSendSuccess<johariCreateJohariAnswerController_OutputDTO>;
export type johariGetJohariAnswersController_UrlParams = z.infer<
  NonNullable<(typeof c.johariGetJohariAnswers)["urlParamsValidator"]>
>;
export type johariGetJohariAnswersController_QueryParams = z.infer<
  NonNullable<(typeof c.johariGetJohariAnswers)["urlQueryParamsValidator"]>
>;
export type johariGetJohariAnswersController_InputDTO = z.infer<
  NonNullable<(typeof c.johariGetJohariAnswers)["requestBodyValidator"]>
>;
export type johariGetJohariAnswersController_OutputDTO = Awaited<
  ReturnType<(typeof c.johariGetJohariAnswers)["httpRequestHandler"]>
>;
export type johariGetJohariAnswersController_OutputFullDTO =
  JSendSuccess<johariGetJohariAnswersController_OutputDTO>;
export type johariCreateJohariController_UrlParams = z.infer<
  NonNullable<(typeof c.johariCreateJohari)["urlParamsValidator"]>
>;
export type johariCreateJohariController_QueryParams = z.infer<
  NonNullable<(typeof c.johariCreateJohari)["urlQueryParamsValidator"]>
>;
export type johariCreateJohariController_InputDTO = z.infer<
  NonNullable<(typeof c.johariCreateJohari)["requestBodyValidator"]>
>;
export type johariCreateJohariController_OutputDTO = Awaited<
  ReturnType<(typeof c.johariCreateJohari)["httpRequestHandler"]>
>;
export type johariCreateJohariController_OutputFullDTO =
  JSendSuccess<johariCreateJohariController_OutputDTO>;
export type leetcodeCreateLeetcodeQuesController_UrlParams = z.infer<
  NonNullable<(typeof c.leetcodeCreateLeetcodeQues)["urlParamsValidator"]>
>;
export type leetcodeCreateLeetcodeQuesController_QueryParams = z.infer<
  NonNullable<(typeof c.leetcodeCreateLeetcodeQues)["urlQueryParamsValidator"]>
>;
export type leetcodeCreateLeetcodeQuesController_InputDTO = z.infer<
  NonNullable<(typeof c.leetcodeCreateLeetcodeQues)["requestBodyValidator"]>
>;
export type leetcodeCreateLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeCreateLeetcodeQues)["httpRequestHandler"]>
>;
export type leetcodeCreateLeetcodeQuesController_OutputFullDTO =
  JSendSuccess<leetcodeCreateLeetcodeQuesController_OutputDTO>;
export type leetcodeGetLeetcodeQuesController_UrlParams = z.infer<
  NonNullable<(typeof c.leetcodeGetLeetcodeQues)["urlParamsValidator"]>
>;
export type leetcodeGetLeetcodeQuesController_QueryParams = z.infer<
  NonNullable<(typeof c.leetcodeGetLeetcodeQues)["urlQueryParamsValidator"]>
>;
export type leetcodeGetLeetcodeQuesController_InputDTO = z.infer<
  NonNullable<(typeof c.leetcodeGetLeetcodeQues)["requestBodyValidator"]>
>;
export type leetcodeGetLeetcodeQuesController_OutputDTO = Awaited<
  ReturnType<(typeof c.leetcodeGetLeetcodeQues)["httpRequestHandler"]>
>;
export type leetcodeGetLeetcodeQuesController_OutputFullDTO =
  JSendSuccess<leetcodeGetLeetcodeQuesController_OutputDTO>;
export type versionController_UrlParams = z.infer<
  NonNullable<(typeof c.version)["urlParamsValidator"]>
>;
export type versionController_QueryParams = z.infer<
  NonNullable<(typeof c.version)["urlQueryParamsValidator"]>
>;
export type versionController_InputDTO = z.infer<
  NonNullable<(typeof c.version)["requestBodyValidator"]>
>;
export type versionController_OutputDTO = Awaited<
  ReturnType<(typeof c.version)["httpRequestHandler"]>
>;
export type versionController_OutputFullDTO =
  JSendSuccess<versionController_OutputDTO>;
export type webhookTelegramController_UrlParams = z.infer<
  NonNullable<(typeof c.webhookTelegram)["urlParamsValidator"]>
>;
export type webhookTelegramController_QueryParams = z.infer<
  NonNullable<(typeof c.webhookTelegram)["urlQueryParamsValidator"]>
>;
export type webhookTelegramController_InputDTO = z.infer<
  NonNullable<(typeof c.webhookTelegram)["requestBodyValidator"]>
>;
export type webhookTelegramController_OutputDTO = Awaited<
  ReturnType<(typeof c.webhookTelegram)["httpRequestHandler"]>
>;
export type webhookTelegramController_OutputFullDTO =
  JSendSuccess<webhookTelegramController_OutputDTO>;
