/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genInfraBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(9c5087e0d6517cb0a3657ad58c363c690b881249504f1f8f020a6203f0b78e47)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as TelegramBotsMuwnoBot } from "../infra/Telegram/Bots/MuwnoBot.in.js";
export { default as TelegramBotsMwBot } from "../infra/Telegram/Bots/MwBot.in.js";
export { default as TelegramBotsWhatchBot } from "../infra/Telegram/Bots/WhatchBot.in.js";
