/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genInfraBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(6d3fe9ac5c6bb3e687f5e1727e3e465ca1298045028077e1c5d0f16a53971cf8)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as TelegramBotsMuwnoBot } from "../infra/TelegramBots/MuwnoBot.in.js";
export { default as TelegramBotsMwBot } from "../infra/TelegramBots/MwBot.in.js";
export { default as TelegramBotsWhatchBot } from "../infra/TelegramBots/WhatchBot.in.js";
