/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpRoutesTable
 *
 * Generated hash in hex for code after this section is:
 * sha256(3b8b893110e2be17e4c49152408a813e62a5f5c6d6d8fba989db3b05d912de3b)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import { Router } from "express";
import * as c from "./httpControllerBarrelFile.generated.do_not_include_in_barrel_file.js";
/**
 * A route tables sort of file, where all HTTP API routes are defined here along
 * with the controllers/route-handlers that will be used to handle requests for
 * the specified route.
 *
 * ### Why do definitions here look so weird?
 * All HTTP route handlers / controllers are defined using `httpController`
 * which allows them to define the (HTTP method, API paths, Route hander) all in
 * the same file.
 *
 * The HTTP methods and API paths are then redefined here again, together with
 * the route handler used to handle them for clarity sake.
 *
 * By doing this, the HTTP methods and API paths are available for developers to
 * see in both the controller file and this main routes table file, which makes
 * it easy to see in both places without having to navigate code / jump around.
 *
 * The definitions are also guaranteed to be kept in sync using the `satisfies`
 * type checking operator, since both the HTTP methods and API paths are defined
 * as type literals!
 */
export function registerRoutesAndControllers() {
  const r = Router();

  // GET /api/
  r["get" satisfies typeof c.healthCheck.method](
    "/" satisfies typeof c.healthCheck.path,
    c.healthCheck.routeHandler,
  );

  // POST /api/v1/blog/subscribe
  r["post" satisfies typeof c.blogNewSubscriber.method](
    ("/v1" satisfies typeof c.blogNewSubscriber.version) +
      ("/blog/subscribe" satisfies typeof c.blogNewSubscriber.path),
    c.blogNewSubscriber.routeHandler,
  );

  // POST /api/v1/bucketlist
  r["post" satisfies typeof c.bucketlistCreateOne.method](
    ("/v1" satisfies typeof c.bucketlistCreateOne.version) +
      ("/bucketlist" satisfies typeof c.bucketlistCreateOne.path),
    c.bucketlistCreateOne.routeHandler,
  );

  // GET /api/v1/bucketlist/:bucketlistID
  r["get" satisfies typeof c.bucketlistGetOne.method](
    ("/v1" satisfies typeof c.bucketlistGetOne.version) +
      ("/bucketlist/:bucketlistID" satisfies typeof c.bucketlistGetOne.path),
    c.bucketlistGetOne.routeHandler,
  );

  // GET /api/v1/check/checklist/:checklistID
  r["get" satisfies typeof c.checkGetChecklist.method](
    ("/v1" satisfies typeof c.checkGetChecklist.version) +
      ("/check/checklist/:checklistID" satisfies typeof c.checkGetChecklist.path),
    c.checkGetChecklist.routeHandler,
  );

  // POST /api/v1/johari/create
  r["post" satisfies typeof c.johariCreateJohari.method](
    ("/v1" satisfies typeof c.johariCreateJohari.version) +
      ("/johari/create" satisfies typeof c.johariCreateJohari.path),
    c.johariCreateJohari.routeHandler,
  );

  // POST /api/v1/leetcode/ques
  r["post" satisfies typeof c.leetcodeCreateLeetcodeQues.method](
    ("/v1" satisfies typeof c.leetcodeCreateLeetcodeQues.version) +
      ("/leetcode/ques" satisfies typeof c.leetcodeCreateLeetcodeQues.path),
    c.leetcodeCreateLeetcodeQues.routeHandler,
  );

  // GET /api/v1/leetcode/ques/:leetcodeQuesID
  r["get" satisfies typeof c.leetcodeGetLeetcodeQues.method](
    ("/v1" satisfies typeof c.leetcodeGetLeetcodeQues.version) +
      ("/leetcode/ques/:leetcodeQuesID" satisfies typeof c.leetcodeGetLeetcodeQues.path),
    c.leetcodeGetLeetcodeQues.routeHandler,
  );

  // GET /api/version
  r["get" satisfies typeof c.version.method](
    "/version" satisfies typeof c.version.path,
    c.version.routeHandler,
  );

  // POST /api/v1/webhook/telegram/:telegramWebhookSecretPath/:telegramBotToken
  r["post" satisfies typeof c.webhookTelegram.method](
    ("/v1" satisfies typeof c.webhookTelegram.version) +
      ("/webhook/telegram/:telegramWebhookSecretPath/:telegramBotToken" satisfies typeof c.webhookTelegram.path),
    c.webhookTelegram.routeHandler,
  );

  return r;
}
