/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModuleRunner
 *
 * Generated hash in hex for code after this section is:
 * sha256(5e34c364bab6e2613dc1c83d4feaba07bea0245a8d423c5c89831465b16b7a46)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import { logger } from "../logging/index.js";
import { unknownCatchToError } from "../utils/index.js";
import { st } from "./startupModulesBarrelFile.generated.js";

/**
 * Runner function that runs all the startup modules concurrently, and stops the
 * process if any of them fails.
 */
export async function startupModuleRunner() {
  try {
    logger.info(startupModuleRunner.name, "Running (1) Startup Modules");

    await Promise.all([
      logBeforeRun(st.telegramRegisterAllTelegramBotWebhookUrls)(),
    ]);
  } catch (e) {
    const error = unknownCatchToError(e);

    logger.error(
      startupModuleRunner.name,
      "Failed while running Startup Module",
      error,
    );

    // Stop the entire process as this should not continue unless all startup
    // modules completed successfully.
    process.exit(1);
  }
}

const logBeforeRun = (fn: () => any) =>
  async function () {
    logger.verbose(`${startupModuleRunner.name}:${fn.name}`, "Start");
    await fn();
    logger.verbose(`${startupModuleRunner.name}:${fn.name}`, "Completed");
  };
