/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(5e0857a00b8d311678edf48c309b13536cac8dc2358950a3773889dc11ef6127)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
