/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(77c47543f22f8c2673d2b92092ac65a823b58d8c1816f2f2e7cbe3ce5e91e420)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as telegramSetupTelegramBots } from "../startup/telegram/setupTelegramBots.st.js";
