/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(7d1edf90242285201bfee6a0a788be84ef4f0a73c237a47a5ec27c2b7d569b07)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as st from "./startupModulesExportFile.generated.do_not_include_in_barrel_file.js";
