/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(8d92dbbe94c8e3bbeca87482d04535aa7a5ce3ba4c2679bfa462954ea53d195d)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as st from "./startupModulesExportFile.generated.do_not_include_in_barrel_file.js";
