/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(40495b597cd19c5534be643791f3b451611f278c73811311dc752db971d9972e)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as st from "./startupModulesExportFile.generated.do_not_include_in_barrel_file.js";
