/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(b3288ac664f567b2bd7273ef921127cb4517700377b888b8953f559afb959653)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as telegramSetupTelegramBots } from "../startup/telegram/setupTelegramBots.st.js";
