/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(f0b3750f18765fae5f54c843b2bba045e5784f93458ab95ba23d50e1d6858e0e)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as urlBuilder from "./httpControllerUrlBuilders.generated.do_not_include_in_barrel_file.js";
