/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(b5722307f8a0f6b809731e25929945cf465b19a5f384e98c2cac1ca27dc80292)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as urlBuilder from "./httpControllerUrlBuilders.generated.do_not_include_in_barrel_file.js";
