/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(e60acbf354bde1c32141c6bcf6346aa90a0a30793547e88ba2f3def3ba339421)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as urlBuilder from "./httpControllerUrlBuilders.generated.do_not_include_in_barrel_file.js";
