/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenAsyncJobTypeBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(e96fc1c027740d660926b220754f0dd4cfe6fd784a1f2cc80af4cf1bb8ad7feb)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as example } from "../../async/jobs/example.job.js";
