/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenAsyncJobTypeMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(981374efacaf06ac7b78d84f928f54801230efaec5903ef6d4df3202e1c5a49a)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { AsyncJobType } from "../../async/AsyncJobType.js";

/**
 * Mapping of `AsyncJobType['ID']` to `AsyncJobType`.
 *
 * Use `import` function to asynchronously load the job definition module, so
 * that they are not all loaded on startup and only lazily loaded whenever they
 * are used.
 */
export const asyncJobTypeMapping: Record<
  string,
  () => Promise<{ default: AsyncJobType<any> }>
> = {
  "3h1s": () => import("../../async/jobs/example.job.js"),
};
