/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenEntOperatorMapping
 *
 * Generated hash in hex for code after this section is:
 * sha256(b291d2fcb337e9fa88984449c8e350cf72be9ed5621db18b33853a5126345676)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type { BaseEnt } from "../../ent/BaseEnt.js";
import type { EntCrudOperator } from "../../ent/EntCrudOperator.js";

import { entOperators } from "./entOperatorsBarrelFile.generated.js";

/**
 * Mapping of `EntTypeID` to `EntOperators`.
 */
export const entOperatorsMapping: Record<string, EntCrudOperator<BaseEnt>> = {
  "40ba": entOperators.EntBlogOperators,
  "0dda": entOperators.EntBlogSubscriberOperators,
  "4f51": entOperators.EntJohariOperators,
  "90f3": entOperators.EntJohariAnswerOperators,
  "48fi": entOperators.EntUserOperators,
};
