/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(99e76c305256a6f8b4361ffaec948ead6218ebad9c9ca84a3fa9ed480d2da5fa)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as httpControllerUrlBuilders from "./httpControllerUrlBuilders.generated.do_not_include_in_barrel_file.js";
