/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenHttpControllerTypeDefinitions
 *
 * Generated hash in hex for code after this section is:
 * sha256(277d811a2c2af0d2d34e7f3f8b272566a1e6ab37f02ec30441bdbf61cc76c0e2)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export * as httpControllerTypeDefinitions from "./httpControllerTypeDefinitions.generated.do_not_include_in_barrel_file.js";
