/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenStartupModuleRunner
 *
 * Generated hash in hex for code after this section is:
 * sha256(e22a4539b90f0f238720f24c342166403f1eb99c9531cb88dd349ad70a62cc2b)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import { simpleLogger } from "../../logging/SimpleLogger.js";
import { st } from "./startupModulesBarrelFile.generated.js";

/**
 * Runner function that runs all the startup modules concurrently, and stops the
 * process if any of them fails.
 */
export async function startupModuleRunner() {
  try {
    simpleLogger.info(startupModuleRunner.name, "Running (1) Startup Modules");

    await Promise.all([logBeforeRun(st.telegramSetupTelegramBots)()]);
  } catch (e) {
    const error = $convertUnknownCatchToError(e);

    simpleLogger.error(
      startupModuleRunner.name,
      "Failed while running Startup Module",
      error,
    );

    // Stop the entire process as this should not continue unless all startup
    // modules completed successfully.
    process.exit(1);
  }
}

const logBeforeRun = (fn: () => any) =>
  async function () {
    simpleLogger.verbose(`${startupModuleRunner.name}:${fn.name}`, "Start");
    await fn();
    simpleLogger.verbose(`${startupModuleRunner.name}:${fn.name}`, "Completed");
  };
