/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * GenStartupModulesBarrelFile
 *
 * Generated hash in hex for code after this section is:
 * sha256(a156caa431777af97176eb94942a88c48dae763cd8bc9f34bc3ce663dfcf3bf1)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
export { default as telegramSetupTelegramBots } from "../../startup/telegram/setupTelegramBots.st.js";
