export function genGeneratedNotice(generator: Function, codeHash: string) {
  return `================================================================================

+++++++++++++++++++++ THIS IS A GENERATED FILE ++++++++++++++++++++++++++++++++

+++++++++++++++++++++ DO NOT MODIFY OR FORMAT MANUALLY +++++++++++++++++++++

This file is automatically generated with the module:  
${generator.name}

Generated hash in hex for the content after this section is:  
${codeHash}

================================================================================
`;
}
