/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(fd98332970e9ab9ea6f1c3a10e5f0b45f37db56a05f5c7afe76c507d8f27cdf9)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  leetcodeGetLeetcodeQuesController_UrlParams,
  leetcodeGetLeetcodeQuesController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  leetcodeGetLeetcodeQuesController_InputDTO,
  leetcodeGetLeetcodeQuesController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForLeetcodeGetLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: leetcodeGetLeetcodeQuesController_UrlParams;
    urlQueryParams: leetcodeGetLeetcodeQuesController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/leetcode/ques/${options.urlParams.leetcodeQuesID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
