/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(c7f572e86c04481550012097b926238ffc7dc290cc3dbb1ece9a900e1e1a0077)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  johariCreateJohariController_UrlParams,
  johariCreateJohariController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  johariCreateJohariController_InputDTO,
  johariCreateJohariController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForJohariCreateJohari = (
  options: UrlBuilderOptions<{
    urlParams: johariCreateJohariController_UrlParams;
    urlQueryParams: johariCreateJohariController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/johari/create${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
