/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(2dd4c05ef852a0883f74247197267294ea5b958b7ffcefcd6855e26a2c838ead)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  leetcodeCreateLeetcodeQuesController_UrlParams,
  leetcodeCreateLeetcodeQuesController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  leetcodeCreateLeetcodeQuesController_InputDTO,
  leetcodeCreateLeetcodeQuesController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForLeetcodeCreateLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: leetcodeCreateLeetcodeQuesController_UrlParams;
    urlQueryParams: leetcodeCreateLeetcodeQuesController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/leetcode/ques${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
