/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(30b340344642692fdcc439c88b013aa240dc8720f1ef4735b31d63a68fb1d28f)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistCreateOneController_UrlParams,
  bucketlistCreateOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  bucketlistCreateOneController_InputDTO,
  bucketlistCreateOneController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBucketlistCreateOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistCreateOneController_UrlParams;
    urlQueryParams: bucketlistCreateOneController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/bucketlist${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
