/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(4fc9208586f7c173561d954f74e72176e04b5f8d520703c9ec2654b9bf3e51bb)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistGetOneController_UrlParams,
  bucketlistGetOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  bucketlistGetOneController_InputDTO,
  bucketlistGetOneController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBucketlistGetOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistGetOneController_UrlParams;
    urlQueryParams: bucketlistGetOneController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/bucketlist/${options.urlParams.bucketlistID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
