/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(497c7720fdbc269aa9f6c2c62c8a5a80d9e14f926f48317028a7d1928d503390)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  johariCreateJohariAnswerController_UrlParams,
  johariCreateJohariAnswerController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  johariCreateJohariAnswerController_InputDTO,
  johariCreateJohariAnswerController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForJohariCreateJohariAnswer = (
  options: UrlBuilderOptions<{
    urlParams: johariCreateJohariAnswerController_UrlParams;
    urlQueryParams: johariCreateJohariAnswerController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/johari/answer${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
