/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(2bb3de74b3bfeada1d41bd3c33332ca8e352610afbe6fe4c642bf88cb0f4f415)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  blogNewSubscriberController_UrlParams,
  blogNewSubscriberController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  blogNewSubscriberController_InputDTO,
  blogNewSubscriberController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBlogNewSubscriber = (
  options: UrlBuilderOptions<{
    urlParams: blogNewSubscriberController_UrlParams;
    urlQueryParams: blogNewSubscriberController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/blog/subscribe${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
