/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(2fda2f25708173dd62f64c910244ab65b325e03ab11541c698666d8ec6d13603)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  healthCheckController_UrlParams,
  healthCheckController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  healthCheckController_InputDTO,
  healthCheckController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForHealthCheck = (
  options: UrlBuilderOptions<{
    urlParams: healthCheckController_UrlParams;
    urlQueryParams: healthCheckController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
