/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(b119e3b27c5e44ee3702af5c91ac67f1499a85dc16aa6ef4b5f879d1c870556c)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  versionController_UrlParams,
  versionController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  versionController_InputDTO,
  versionController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForVersion = (
  options: UrlBuilderOptions<{
    urlParams: versionController_UrlParams;
    urlQueryParams: versionController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/version${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
