/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(55d8d4bbafdb240b864f865f50c13eb8280f392f221049de25865a0c89259f27)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  johariGetJohariController_UrlParams,
  johariGetJohariController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  johariGetJohariController_InputDTO,
  johariGetJohariController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForJohariGetJohari = (
  options: UrlBuilderOptions<{
    urlParams: johariGetJohariController_UrlParams;
    urlQueryParams: johariGetJohariController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/johari/${options.urlParams.johariID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
