/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(ee0864bde207a9183b5fe9615dc2f69bf38178aff9ea67386a1114356eecfe84)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  johariGetJohariAnswersController_UrlParams,
  johariGetJohariAnswersController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  johariGetJohariAnswersController_InputDTO,
  johariGetJohariAnswersController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForJohariGetJohariAnswers = (
  options: UrlBuilderOptions<{
    urlParams: johariGetJohariAnswersController_UrlParams;
    urlQueryParams: johariGetJohariAnswersController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/johari/answers/${options.urlParams.johariID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
