/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(b03edcc980a761ad14e4883f076d2c6fb8c525a17211519f47f5a955a53669b5)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  leetcodeCreateLeetcodeQuesController_UrlParams,
  leetcodeCreateLeetcodeQuesController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  leetcodeCreateLeetcodeQuesController_InputDTO,
  leetcodeCreateLeetcodeQuesController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForLeetcodeCreateLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: leetcodeCreateLeetcodeQuesController_UrlParams;
    urlQueryParams: leetcodeCreateLeetcodeQuesController_QueryParams;
  }>,
) =>
  `${process.env["BASE_URL_TO_SELF"]}/api/v1/leetcode/ques${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
