/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(14e5b67c9f5aac4affeef5d942208216f81532c59b8ad15fea612dfeace90505)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  blogNewSubscriberController_UrlParams,
  blogNewSubscriberController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForBlogNewSubscriber = (
  options: UrlBuilderOptions<{
    urlParams: blogNewSubscriberController_UrlParams;
    urlQueryParams: blogNewSubscriberController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/blog/subscribe${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
