/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(3226b627519a745a41e39bcac93edc80a865caab3ab7abed56d90884c9cf2767)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistCreateOneController_UrlParams,
  bucketlistCreateOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  bucketlistCreateOneController_InputDTO,
  bucketlistCreateOneController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBucketlistCreateOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistCreateOneController_UrlParams;
    urlQueryParams: bucketlistCreateOneController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/bucketlist${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
