/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(cf6c8213cf1ce1496a3659f06971897e1ec1de646b389307aa1d7fe54931409d)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistCreateOneController_UrlParams,
  bucketlistCreateOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForBucketlistCreateOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistCreateOneController_UrlParams;
    urlQueryParams: bucketlistCreateOneController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/bucketlist${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
