/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(c9063176638322214a285adc359a4bb76afd2440814e89943dc75829ab6e53f9)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type * as t from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForLeetcodeCreateLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: t.leetcodeCreateLeetcodeQuesController_UrlParams;
    urlQueryParams: t.leetcodeCreateLeetcodeQuesController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/leetcode/ques${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
