/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(d620855202d195ea1bd79ab0c85e1922d85c58d02d6936083fb27e8b5424b835)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  blogNewSubscriberController_UrlParams,
  blogNewSubscriberController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  blogNewSubscriberController_InputDTO,
  blogNewSubscriberController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBlogNewSubscriber = (
  options: UrlBuilderOptions<{
    urlParams: blogNewSubscriberController_UrlParams;
    urlQueryParams: blogNewSubscriberController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/blog/subscribe${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
