/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(f6ea6e3dfeccbb2e41bd637b45635a2cb46fb8a44698a7654ad68b0476eca1b8)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type * as t from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForVersion = (
  options: UrlBuilderOptions<{
    urlParams: t.versionController_UrlParams;
    urlQueryParams: t.versionController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/version${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
