/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(6b5e9e5b3890d43932169479020084a756ee89da9a56e90828bec7c2fd987332)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistGetOneController_UrlParams,
  bucketlistGetOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForBucketlistGetOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistGetOneController_UrlParams;
    urlQueryParams: bucketlistGetOneController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/bucketlist/${options.urlParams.bucketlistID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
