/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(5bfa17512efdc22bb714c27db3501811ca10c7e90702ec0df97ebdeed6969267)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  bucketlistGetOneController_UrlParams,
  bucketlistGetOneController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  bucketlistGetOneController_InputDTO,
  bucketlistGetOneController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForBucketlistGetOne = (
  options: UrlBuilderOptions<{
    urlParams: bucketlistGetOneController_UrlParams;
    urlQueryParams: bucketlistGetOneController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/bucketlist/${options.urlParams.bucketlistID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
