/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(1eb718f312f96bc9f660c631ae076de4814d33f991477e37b63338efd8abc216)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  leetcodeCreateLeetcodeQuesController_UrlParams,
  leetcodeCreateLeetcodeQuesController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForLeetcodeCreateLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: leetcodeCreateLeetcodeQuesController_UrlParams;
    urlQueryParams: leetcodeCreateLeetcodeQuesController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/leetcode/ques${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
