/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(2791f28e8eabe1d57a31c051a896c06839695c8c52fa17973cf5a90d33e9bfb5)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  leetcodeGetLeetcodeQuesController_UrlParams,
  leetcodeGetLeetcodeQuesController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export type {
  leetcodeGetLeetcodeQuesController_InputDTO,
  leetcodeGetLeetcodeQuesController_OutputDTO,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";

export const urlBuilderForLeetcodeGetLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: leetcodeGetLeetcodeQuesController_UrlParams;
    urlQueryParams: leetcodeGetLeetcodeQuesController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/leetcode/ques/${options.urlParams.leetcodeQuesID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
