/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(cf9774eaa04706ae2e99a3cadcd017b6c4866992daf18bd7ad8d0a3c1e62427b)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type {
  versionController_UrlParams,
  versionController_QueryParams,
} from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForVersion = (
  options: UrlBuilderOptions<{
    urlParams: versionController_UrlParams;
    urlQueryParams: versionController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/version${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
