/**
 * ********************* THIS IS A GENERATED FILE *****************************
 * ********************* DO NOT MODIFY OR FORMAT MANUALLY *********************
 *
 * This file is automatically generated with the module:
 * genStandaloneHttpControllerUrlBuilders
 *
 * Generated hash in hex for code after this section is:
 * sha256(514ffad365dcc69f7ae15fe0ca9ef612234d0c406a37cd2a09ee9cb126f06612)
 */
/* eslint-disable perfectionist/sort-imports */
/* eslint-disable perfectionist/sort-exports */
import type * as t from "../../../__generated/httpControllerTypeDefinitions.generated.js";
import type { UrlBuilderOptions } from "./UrlBuilderOptions.generated.js";

import { createUrlQueryParamsString } from "./createUrlQueryParamsString.generated";

export const urlBuilderForLeetcodeGetLeetcodeQues = (
  options: UrlBuilderOptions<{
    urlParams: t.leetcodeGetLeetcodeQuesController_UrlParams;
    urlQueryParams: t.leetcodeGetLeetcodeQuesController_QueryParams;
  }>,
) =>
  `http://localhost:3000/api/v1/leetcode/ques/${options.urlParams.leetcodeQuesID}${createUrlQueryParamsString((options as any)?.urlQueryParams)}`;
